#!/bin/bash

if [ -z "$2" ]; then
   echo "USAGE: findcode <file extension> <regex>"
   exit
fi

dir="."

[ -z "$3" ] || dir="$3"

for filename in `find $dir -name "*$1"`
   do grep -H $2 $filename
done

exit 0
