#!/bin/bash

if [ -z "$2" ]; then
   echo "USAGE: findline <regex> <file extension>"
   exit
fi

dir="."

[ -z "$3" ] || dir="$3"

for filename in `find $dir -name "*$2"`
   do grep -H $1 $filename
done

exit 0
